dev:
  build: .
  dockerfile: Dockerfile
  volumes:
   - ".:/vagrant"
   - ".:/vagrant_bind"
  environment:
   - PYTHONDONTWRITEBYTECODE=true
   - NODE_PATH=/vagrant-dev/node_modules/
   - GGRC_DATABASE_URI=mysql+mysqldb://root:root@db/ggrcdev?charset=utf8
   - GGRC_DATABASE_HOST=db
  links:
   - db

db:
  image: mysql:5.6
  volumes:
   - "./provision/docker/mysql:/etc/mysql/conf.d"
  environment:
   - MYSQL_ROOT_PASSWORD=root

selenium:
  build: .
  dockerfile: Dockerfile-selenium
  volumes:
   - "./test/selenium:/selenium"
   - "/dev/shm:/dev/shm"
  links:
   - dev
  environment:
   - PYTHONDONTWRITEBYTECODE=true
   - PYTHONPATH=/selenium/src
   - SCREEN_WIDTH=1440
   - SCREEN_HEIGHT=900
